export const dummy = {
  dates: { maximum: "2024-06-19", minimum: "2024-05-08" },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/fqv8v6AycXKsivp1T5yKtLbGXce.jpg",
      genre_ids: [878, 12, 28],
      id: 653346,
      original_language: "en",
      original_title: "Kingdom of the Planet of the Apes",
      overview:
        "진화한 유인원과 퇴화된 인간들이 살아가는 땅. 유인원 리더 프록시무스는 완전한 군림을 위해 인간들을 사냥하며 자신의 제국을 건설한다. 한편, 또 다른 유인원 노아는 우연히 숨겨진 과거의 이야기와 시저의 가르침을 듣게 되고 인간과 유인원이 함께 할 새로운 세상을 꿈꾼다. 어느 날 그의 앞에 나타난 의문의 한 인간 소녀. 노아는 그녀와 함께 자유를 향한 여정을 시작하게 되는데…",
      popularity: 4050.674,
      poster_path: "/plNOSbqkSuGEK2i15A5btAXtB7t.jpg",
      release_date: "2024-05-08",
      title: "혹성탈출: 새로운 시대",
      video: false,
      vote_average: 6.88,
      vote_count: 943,
    },
    {
      adult: false,
      backdrop_path: "/ga4OLm4qLxPqKLMzjJlqHxVjst3.jpg",
      genre_ids: [28, 80, 53],
      id: 573435,
      original_language: "en",
      original_title: "Bad Boys: Ride or Die",
      overview:
        "마이애미 강력반 최고의 콤비 마이크와 마커스. 가족 같은 하워드 반장이 사망 전 마약 카르텔 조직의 비리에 연루되었다는 뉴스 속보를 접하게 된다. 하지만 아무도 믿지 말라는 하워드 반장의 비밀 메시지를 받은 마이크와 마커스 형사는 사건의 진실을 밝히기 위해 위험한 수사를 시작한다. 서서히 드러나는 거대한 음모와 마주하게 된 나쁜 녀석들. 그러나 이들 역시 함정에 빠져 사건의 용의자로 지목되며 동료 경찰들은 물론 마약 카르텔 조직에게도 쫓기는 신세가 되고 마는데…",
      popularity: 2779.49,
      poster_path: "/nP6RliHjxsz4irTKsxe8FRhKZYl.jpg",
      release_date: "2024-06-06",
      title: "나쁜 녀석들: 라이드 오어 다이",
      video: false,
      vote_average: 7.183,
      vote_count: 150,
    },
    {
      adult: false,
      backdrop_path: "/uVu2fBc114un7F1GD76RBouWyBP.jpg",
      genre_ids: [16, 10751, 18, 12, 35],
      id: 1022789,
      original_language: "en",
      original_title: "Inside Out 2",
      overview:
        "13살이 된 라일리의 행복을 위해 매일 바쁘게 머릿속 감정 컨트롤 본부를 운영하는 ‘기쁨’, ‘슬픔’, ‘버럭’, ‘까칠’, ‘소심’. 그러던 어느 날, 낯선 감정인 ‘불안’, ‘당황’, ‘따분’, ‘부럽’이가 본부에 등장하고, 언제나 최악의 상황을 대비하며 제멋대로인 ‘불안’이와 기존 감정들은 계속 충돌한다. 결국 새로운 감정들에 의해 본부에서 쫓겨나게 된 기존 감정들은 다시 본부로 돌아가기 위해 위험천만한 모험을 시작하는데…",
      popularity: 1810.424,
      poster_path: "/pmemGuhr450DK8GiTT44mgwWCP7.jpg",
      release_date: "2024-06-12",
      title: "인사이드 아웃 2",
      video: false,
      vote_average: 8.1,
      vote_count: 26,
    },
    {
      adult: false,
      backdrop_path: "/7v4gev91nO3i66Zzygh9jplu9UI.jpg",
      genre_ids: [28, 12, 878],
      id: 786892,
      original_language: "en",
      original_title: "Furiosa: A Mad Max Saga",
      overview:
        "문명 붕괴 45년 후, 황폐해진 세상 속 누구에게도 알려지지 않은 풍요가 가득한 녹색의 땅에서 자란 퓨리오사는 바이커 군단의 폭군 디멘투스의 손에 모든 것을 잃고 만다. 가족도 행복도 모두 빼앗기고 세상에 홀로 내던져진 퓨리오사는 반드시 고향으로 돌아가겠다는 어머니와의 약속을 지키기 위해 인생 전부를 건 복수를 시작하는데...",
      popularity: 830.65,
      poster_path: "/zaUFDdJidS4Nyyd6jb2Ok3Kq4Vo.jpg",
      release_date: "2024-05-22",
      title: "퓨리오사: 매드맥스 사가",
      video: false,
      vote_average: 7.656,
      vote_count: 827,
    },
    {
      adult: false,
      backdrop_path: "/vWzJDjLPmycnQ42IppEjMpIhrhc.jpg",
      genre_ids: [16, 35, 10751, 12],
      id: 748783,
      original_language: "en",
      original_title: "The Garfield Movie",
      overview:
        "세상귀찮 집냥이, 바쁘고 험난한 세상에 던져졌다! 집사 ‘존’과 반려견 ‘오디’를 기르며 평화로운 나날을 보내던 집냥이 ‘가필드’. 어느 날, 험악한 길냥이 무리에게 납치당해 냉혹한 거리로 던져진다. 돌봐주는 집사가 없는 집 밖 세상은 너무나도 정신없게 돌아가고 길에서 우연히 다시 만난 아빠 길냥이 ‘빅’은 오히려 ‘가필드’를 위기에 빠지게 하는데… 험난한 세상, 살아남아야 한다!",
      popularity: 514.952,
      poster_path: "/57g3pHYi3p0JNVO1LkcyYbeMDBf.jpg",
      release_date: "2024-05-15",
      title: "가필드 더 무비",
      video: false,
      vote_average: 6.4,
      vote_count: 155,
    },
    {
      adult: false,
      backdrop_path: "/nv6F6tz7r61DUhE7zgHwLJFcTYp.jpg",
      genre_ids: [10749, 35, 80],
      id: 974635,
      original_language: "en",
      original_title: "Hit Man",
      overview:
        "경찰의 의뢰로 부업 삼아 살인 청부업자 행세를 하는 온화한 성품의 교수. 그런 그가 잠재 고객에게 끌리기 시작하면서 여러 문제가 연쇄적으로 터져 나온다.",
      popularity: 634.928,
      poster_path: "/zREAzThdoALNhci72PuN3bH22BZ.jpg",
      release_date: "2024-05-24",
      title: "히트맨",
      video: false,
      vote_average: 7,
      vote_count: 176,
    },
    {
      adult: false,
      backdrop_path: "/nxxCPRGTzxUH8SFMrIsvMmdxHti.jpg",
      genre_ids: [35, 14, 10751],
      id: 639720,
      original_language: "en",
      original_title: "IF",
      overview:
        "상상의 친구 ‘이프’를 볼 수 있는 능력을 지닌 한 소녀가 아이들에게 잊혀졌던 ‘이프’를 다시 되찾아주기 위해 마법 같은 모험을 시작하는 이야기를 그린 영화",
      popularity: 301.269,
      poster_path: "/9GAOhSzXjXJR4AxYCa2AMzMGPVg.jpg",
      release_date: "2024-05-15",
      title: "이프: 상상의 친구",
      video: false,
      vote_average: 7.1,
      vote_count: 126,
    },
    {
      adult: false,
      backdrop_path: "/ySgY4jBvZ6qchrxKnBg4M8tZp8V.jpg",
      genre_ids: [27, 53],
      id: 1111873,
      original_language: "en",
      original_title: "Abigail",
      overview:
        "오직 돈을 위해서 업계 최고들로만 모인 납치범들. 정체를 알 수 없는 거부의 딸이자 평범한 소녀 애비게일을 납치하고, 24시간 동안 저택에서 그녀를 감시하고 거액의 돈을 받기로 한다. 하지만 평범한 소녀 애비게일은 발레리나 뱀파이어였고 오히려 납치범들은 역으로 저택에 갇혀 그녀의 장난감과 먹이가 되었다. 납치범들은 이제 24시간 안에 살기 위해 저택을 탈출해야 한다.",
      popularity: 322.875,
      poster_path: "/dRCVYbOjhMNghBQgHuqthG5iLH.jpg",
      release_date: "2024-05-15",
      title: "애비게일",
      video: false,
      vote_average: 6.82,
      vote_count: 687,
    },
    {
      adult: false,
      backdrop_path: "/cZmOrIOkJ2SNfVdiO85dUbOAYnL.jpg",
      genre_ids: [16, 18],
      id: 1012201,
      original_language: "ja",
      original_title: "劇場版ハイキュー!! ゴミ捨て場の決戦",
      overview:
        "봄철 고교 배구대회 미야기현 대표 결정전. 1회전과 2회전에서 우승 후보를 차례로 꺾은 카라스노 고등학교는 마침내 3회전에서 인연의 라이벌 네코마 고등학교와 맞붙게 된다. 공식 경기에서 처음으로 대결하는 두 고등학교, 통칭 까마귀 VS 고양이 ‘쓰레기장의 결전’. 약속의 땅에서 ‘한 번 더’가 없는 싸움이 드디어 시작된다!",
      popularity: 203.212,
      poster_path: "/d0jCRbTdJPEvGaboeZ3fvCUVrNT.jpg",
      release_date: "2024-05-15",
      title: "극장판 하이큐!! 쓰레기장의 결전",
      video: false,
      vote_average: 7.359,
      vote_count: 32,
    },
    {
      adult: false,
      backdrop_path: "/4yrOyO3N55XazHQXXYoqiiPQd40.jpg",
      genre_ids: [27],
      id: 938614,
      original_language: "en",
      original_title: "Late Night with the Devil",
      overview:
        "1977년 핼러윈 전날 밤, 시청률을 위해서라면 일단 틀고 보는 방송국 놈들 때문에 누구도 예상하지 못한 방송사고 발생! 그리고 마침내 미국 전역을 충격에 빠트렸던 그날 밤의 생방송 악마와의 토크쇼 녹화영상이 최근에 발견됐는데… 47년간 숨겨진, 절대 생중계돼서는 안 될 최악의 토크쇼가 마침내 공개된다, 그동안 공개되지 않은 비하인드 영상과 함께!",
      popularity: 162.379,
      poster_path: "/5nUu9y8hQtmW4Qt5GWZZATCjFnN.jpg",
      release_date: "2024-05-08",
      title: "악마와의 토크쇼",
      video: false,
      vote_average: 7.277,
      vote_count: 458,
    },
    {
      adult: false,
      backdrop_path: "/aPQsU3yLDUOhLJYnSqkhKRkQTAw.jpg",
      genre_ids: [36, 18],
      id: 467244,
      original_language: "en",
      original_title: "The Zone of Interest",
      overview:
        "독일 장교 루돌프 회스의 가족이 사는 그들만의 꿈의 왕국 아우슈비츠. 아내 헤트비히가 정성스럽게 가꾼 꽃이 만발한 정원에는 재잘거리는 아이들의 웃음소리로 가득하다. 마치 한 폭의 그림 같은 집. 과연 악마는 다른 세상을 사는가?",
      popularity: 87.811,
      poster_path: "/qqXQERsbWGrUldJjr0fDHuWjhPG.jpg",
      release_date: "2024-06-05",
      title: "존 오브 인터레스트",
      video: false,
      vote_average: 7.199,
      vote_count: 1370,
    },
    {
      adult: false,
      backdrop_path: "/lA6KdSkCTxwzvqzPqxch997RabQ.jpg",
      genre_ids: [28, 53],
      id: 560016,
      original_language: "en",
      original_title: "Monkey Man",
      overview:
        "잔혹한 과거의 잔상에서 벗어나지 못하고 괴로워하는 키드. 자신의 가족을 몰살한 경찰청장 라나 싱에게 복수하기 위해 인생을 바친 복수를 계획하지만 순간의 실수로 물거품이 된다. 복수에 실패해 경찰에 쫓기는 신세가 된 키드는 치명상을 입고 목숨을 잃을 위기에 처하지만 비밀스러운 조력자 히즈라들의 도움으로, 힘의 신 몽키맨으로 다시 태어난다.",
      popularity: 91.409,
      poster_path: "/9hEdO3PcV0usDgRyfWOxGYAcoPB.jpg",
      release_date: "2024-06-19",
      title: "몽키맨",
      video: false,
      vote_average: 7.087,
      vote_count: 490,
    },
    {
      adult: false,
      backdrop_path: "/zz219ZRGo0vVIzvKttjx5nXOc2N.jpg",
      genre_ids: [18, 10749, 10402],
      id: 1020006,
      original_language: "en",
      original_title: "Priscilla",
      overview:
        "독일 미군 기지의 어느 파티에서 엘비스 프레슬리와 조우한 10대 소녀 프리실라 볼리외. 당시 이미 초대형 로큰롤 슈퍼스타였던 엘비스였지만, 프리실라와 단둘일 때 그는 전혀 의외의 면모를 보여준다. 그는 황홀한 연애 상대이면서도, 고독한 이의 동반자이자 상처받기 쉬운 단짝이기도 했다.",
      popularity: 80.315,
      poster_path: "/w2Inh0CsdRmuEPrkhLZzXbi94M2.jpg",
      release_date: "2024-06-19",
      title: "프리실라",
      video: false,
      vote_average: 6.9,
      vote_count: 602,
    },
    {
      adult: false,
      backdrop_path: "/qu27OPbaIO9OBj3zd4h9bdS6e58.jpg",
      genre_ids: [10749, 18],
      id: 1188258,
      original_language: "zh",
      original_title: "青春18x2 君へと続く道",
      overview:
        "18년 전의 대만 타이난. 노래방에서 아르바이트를 하는 고등학생 ‘지미’는, 배낭여행 중 잠시 일자리를 찾아 온 일본인 ‘아미’를 만난다. 천진난만한 그녀와 지내는 동안 풋풋한 첫사랑의 감정이 자라는 ‘지미’. 그러나, 돌연 ‘아미’가 귀국을 하게 되고 갑작스런 이별에 충격을 받은 ‘지미’에게 ‘아미’는 서로의 꿈을 이룬 뒤 다시 만나자는 약속을 하고 떠난다. 시간이 지나 현재. 타이페이에서의 성공한 삶에 지쳐 고향에 돌아온 ‘지미’는, 예전에 ‘아미’로부터 받은 그림엽서를 발견한다. 첫사랑의 기억이 되살아나고 그날의 약속을 지키기 위해 그녀가 나고 자란 일본으로의 여행을 결심하는 ‘지미’. 도쿄부터 가마쿠라, 나가노, 니가타 그리고 ‘아미’의 고향 타다미로 향하는 도중 예기치 않았던 소중한 만남을 되풀이하며 ‘지미’는 ‘아미’와 보냈던 그 여름의 나날들을 떠올린다. 이윽고 다다른 ‘아미’의 고향에서 ‘지미’가 알게 된 18년 전 ‘아미’의 진짜 마음이란...",
      popularity: 43.805,
      poster_path: "/6DEvozkU7JoHayFPHA7gsOoYi8C.jpg",
      release_date: "2024-05-22",
      title: "청춘 18X2 너에게로 이어지는 길",
      video: false,
      vote_average: 6.1,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: "/9qBCO17J7XoUFBPck1JWLBS87s2.jpg",
      genre_ids: [10749, 18],
      id: 964960,
      original_language: "fr",
      original_title: "La passion de Dodin Bouffant",
      overview:
        "1885년, 유진은 유명한 미식가 도댕을 위해 20년간 일해 온 최고의 요리사이다. 이 둘의 조합은 세계에서 가장 유명한 요리사 마저 놀라게 할 정도로 훌륭한 요리를 만들어 낸다. 시간이 지나면서 둘은 서로에게 빠지게 되지만, 자유로운 삶을 원하는 유진은 도댕과 결혼하고 싶지 않아한다. 그래서 도댕은 한 번도 해보지 않은 일을 하기로 결심한다. 바로 유진을 위해 요리하는 것.",
      popularity: 59.217,
      poster_path: "/xTjLY87DZJ3y6t9DTqqbgqGyRL2.jpg",
      release_date: "2024-06-19",
      title: "프렌치 수프",
      video: false,
      vote_average: 7.1,
      vote_count: 155,
    },
    {
      adult: false,
      backdrop_path: "/2WRe1y5S1jGWTKUcSPPmD1Ixq56.jpg",
      genre_ids: [35, 14],
      id: 823482,
      original_language: "en",
      original_title: "Dream Scenario",
      overview:
        "소심하고, 한심하고, 평범 그 자체여서 언제 어디서나 존재감 없는 ‘폴’로 인해 온 세상이 떠들썩해진다! 왜? 그가 지구상 모두의 꿈에 나타나고 있기 때문에! “실존 인물 맞나요? 왜 당신 꿈을 꾸죠? 도대체 누구세요?” SNS 메시지 폭주, 인터뷰 출연, 광고 모델 요청은 물론, 심지어 꿈속 만남이 현실로 이어지는 기막힌 일까지! 꿈속 남자에서 모두가 꿈꾸는 남자로 거듭난 ‘폴’! 하지만 갑자기 그가 등장하는 모든 꿈들이 악몽이 되는데…",
      popularity: 45.809,
      poster_path: "/uarf91ft8eVDGMgMH4o6ip7rkCm.jpg",
      release_date: "2024-05-29",
      title: "드림 시나리오",
      video: false,
      vote_average: 6.718,
      vote_count: 659,
    },
    {
      adult: false,
      backdrop_path: "/mSQiMJyuQuHpsZSek10V1sXy8do.jpg",
      genre_ids: [16, 9648, 80],
      id: 1244064,
      original_language: "ja",
      original_title: "TVシリーズ特別編集版『名探偵コナン vs. 怪盗キッド』",
      overview:
        "암호가 섞인 예고장이 보내진 그곳에는 월하의 마술사, 괴도 키드가 나타난다. 세상을 떠들썩하게 만들며 인기를 얻고 있는 그의 정체는 에코다 고등학교 2학년 쿠로바 카이토. 수수께끼의 조직에 살해당한 세계적인 마술사였던 아버지 쿠로바 도이치의 뒤를 이어 사건의 진상을 파헤치기 위해 2대 ‘괴도 키드’가 되어 도이치가 쫓던 ‘빅 주얼’과 조직의 정체를 향해 다가간다. 이번에 그가 노리는 ‘빅 주얼’은 ‘대해의 기적’이자 ‘블루 원더’라고 불리는 전설의 아쿠아마린. 소노코의 친척이자 키드 체포에 열을 올리고 있는 스즈키 지로키치가 그에게 먼저 도전장을 내밀고, 언제나 그랬듯 괴도 키드는 모두의 예상을 뒤엎고 신출귀몰한 방법으로 나타나는데… 이를 막기 위해 불가능을 모르는 명탐정, 코난의 명추리가 펼쳐진다!",
      popularity: 36.893,
      poster_path: "/jXFLbuGUOv7AwIylZwIe97vJOS1.jpg",
      release_date: "2024-06-05",
      title: "명탐정 코난 VS 괴도 키드",
      video: false,
      vote_average: 2,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: "/jBNBEKmY7m511lsF4yQ5awJDMf3.jpg",
      genre_ids: [27, 53],
      id: 1145291,
      original_language: "ja",
      original_title: "禁じられた遊び",
      overview:
        "평범한 회사원 ‘나오토’는 아내 ‘미유키’, 아들 ‘하루토’와 행복하고 단란한 생활을 보내며 이보다 더 완벽할 수 없다고 생각한다. 그러나, 어느 날 ‘미유키’가 갑작스런 교통사고로 세상을 떠나게 되고 부자는 실의에 빠진다. 엄마를 되살리고 싶다는 강한 욕망에 사로잡힌 ‘하루토’. 결국 해서는 안될 금지된 의식을 치르고 끔찍한 재앙이 그들에게 다가오기 시작하는데…",
      popularity: 23.265,
      poster_path: "/9thVJX7sPV6si0580yQXK838AOZ.jpg",
      release_date: "2024-06-05",
      title: "금지된 장난",
      video: false,
      vote_average: 5.3,
      vote_count: 17,
    },
    {
      adult: false,
      backdrop_path: "/6uKXrsdguwZrtG5BL1wBHvxWs3Z.jpg",
      genre_ids: [28, 80, 53],
      id: 557946,
      original_language: "en",
      original_title: "Last Looks",
      overview:
        "홀로 산에 있는 트레일러에 은둔하고 있는 전직 형사 찰리 왈도에게, 어느 날 전 연인인 로레나가 찾아온다.  그녀의 요청은 모니카 핀치 살인 사건을 수사해 달라는 것.  그녀의 남편이자 유명 영화 배우인 앨러스테어 핀치가 유력한 살해 용의자이지만,  아직 드라마 출연분을 채워야 하는 네트워크의 대표인 시고르스키는 그가 혐의를 벗기를 바라고 있다.  로레나에게는 사건을 맡기를 거절했지만,  그가 합류한다는 기사를 보고 갱단 패거리들이 찾아와 그를 협박하고, 설상가상으로 로레나는 행방불명된다.  왈도는 고요했던 은둔 생활을 뒤로 하고, 일을 바로잡으러 시끌벅적한 LA 세상 밖으로 나오게 되는데…",
      popularity: 37.208,
      poster_path: "/brKmmJHmLDdgWNThBgCwgKOBcIk.jpg",
      release_date: "2024-05-08",
      title: "할리우드 살인사건",
      video: false,
      vote_average: 5.9,
      vote_count: 285,
    },
    {
      adult: false,
      backdrop_path: "/s9GMagopY0MrXaAk4zqsDtVjT9Y.jpg",
      genre_ids: [18, 10751],
      id: 1075966,
      original_language: "no",
      original_title: "Dancing Queen",
      overview:
        "16만 팔로워를 가진 힙합 댄서 E.D.윈에게 첫눈에 반한 12살 소녀 미나는 운 좋게 오디션을 통과하고 E.D.윈의 댄스 크루에 들어간다. 공부와 달리 마음대로 되지 않는 몸에 인생 첫 좌절을 마주한 미나. 하지만 포기란 없다! 한때 춤으로 이름 좀 날렸던 할머니의 지도하에 남사친 마르쿠스와 비밀스러운 연습을 시작하는데…",
      popularity: 21.114,
      poster_path: "/1evBzXIC4dghPeK2UaxEwRVw2KM.jpg",
      release_date: "2024-05-29",
      title: "오늘부터 댄싱퀸",
      video: false,
      vote_average: 6.2,
      vote_count: 2,
    },
  ],
  total_pages: 4,
  total_results: 68,
};
